### PR TITLE
NUMBERS-113: Fix JUnit dependencies in pom.xml

### PR DESCRIPTION
**Pull request by Schamschi**
I'm not a JUnit expert, so I'm not sure if this is the optimal way to import both JUnit 5 and JUnit 4. But it does seem to solve the problems described in the JIRA ticket, so I'll just be bold and put this here.

### CODE REVIEW

**Comment by aherbert** [comment]
I think that @grimreaper may have pushed over the original PR #47 that passed all the checks with a different revision. Hopefully it can be sorted quickly.

**Comment by grimreaper** [comment]
hrm, you're right. I thought I pushed the version with the BOM but apparently not.

**Comment by grimreaper** [comment]
@aherbert I think I fixed it now.

**Comment by grimreaper** [comment]
See 6bcc6d9a16bea265243f68b298713d10abb09224

**Comment by aherbert** [comment]
The JUnit change is now restored in master. @Schamschi can you confirm if this has fixed your JUnit issues on your branch and close?

**Comment by Schamschi** [comment]
@aherbert Yes, it seems fixed now, I'm going to close the pull request and the JIRA ticket.

**Pull request closed without merging**
