### PR TITLE
[WIP] perform the actual migration to JUnit 5

### PR DESCRIPTION
**Pull request by grimreaper**
**feel free to push changes to this branch**

This migrates most of the tests to JUnit 5 -
though it doesn't migration the assertions library itself.

Currently broken is the FieldParametricTest since I didn't finish migrating
the parameterization. That will happen 'soon'

### CODE REVIEW

**Comment by Schamschi** [comment]
OK, I've created a [branch](https://github.com/Schamschi/commons-numbers/tree/MigrateToJunit5) too in my fork for the migration to JUnit 5, since I cannot push directly to this branch. I already had some of the test classes fully migrated and committed in my local repository before you created this branch, so there were some merge conflicts when I rebased my local branch onto yours, but I've reviewed them all, and the only conflicting changes made by you I've overwritten were the imports and the parentheses next to the previously parameterized Test annotations for test methods where an exception should be thrown.

I'm not sure, but i think that, if the branches are merged via GitHub, GitHub creates an extra merge commit, making the history look ugly, so maybe you'd prefer to pull my branch into your local repository and push it to this branch, provided you agree with my commits. But I've only been here for a short while, so I don't know what the usual modus operandi in situations like this is.

**Comment by grimreaper** [comment]
@Schamschi lets work off of this branch (I could give you write access). once we have a correct diff, I'll squash and commit (giving you appropriate credit). This way we could use git for development, but avoid merge commits.

**Comment by grimreaper** [comment]
I invited you to edit my fork of commons-numbers.

**Comment by Schamschi** [comment]
Excellent, thanks. I suggest that we wait with the fraction module until the branch fraction-dev is merged to the master branch, to reduce the chance of conflict.

**Comment by grimreaper** [comment]
@Schamschi I just merged master and pushed. Note this is a force-push so you may need to recreate the branch (I'm not 100% sure why that was required, but what's done is done)

**Comment by Schamschi** [comment]
Thanks for letting me know, and it's a good thing you did, because with this force push, you overwrote my migrations of 13 classes from the gamma module, which I had already pushed to the branch. Luckily, I still had them saved in my local repository so I could re-commit them, but the next time you do this, could you please first update your local copy of the branch?

Also, when you merged the master branch, you overwrote several changes from the fraction-dev branch when resolving the arisen merge conflicts. Some of these overwrites were beneficial, e.g. converting tabs to spaces or removing redundant whitespace, but some, i.e. those where you refactored the code to use assertThrows, were problematic, because in some cases the merge from the fraction-dev branch to the master branch caused the test methods to invoke different methods/constructors than before, and when you resolved the merge conflicts, you reverted the test methods to invoke the old methods/constructors, which in some cases did not exist anymore, causing the code to be not compilable.

I think I have fixed these issues now with my latest commmit.

**Comment by grimreaper** [comment]
> but the next time you do this, could you please first update your local copy of the branch?
I think I figured out what I did wrong: my branch was set up to track origin/master instead of our working branch. thus, when I did `git pull` it didn't actually do what I wanted. 

> because in some cases the merge from the fraction-dev branch to the master branch caused the test methods to invoke different methods/constructors than before, ... I think I have fixed these issues now with my latest commit.

Thank you.

Right now the only things failing are
```
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[39,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[40,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[41,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[44,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[45,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] /Users/eax/svn/apache/commons/numbers/commons-numbers-arrays/src/test/java/org/apache/commons/numbers/arrays/LinearCombinationTest.java:[46,29] incompatible types: long cannot be converted to java.math.BigInteger
[ERROR] -> [Help 1]
```` 

which I'm looking at now

**Comment by Schamschi** [comment]
@grimreaper Indeed, this class does not compile (I hadn't noticed until now), however, this has nothing to do with your merge. It was the merging of the fraction-dev branch into the master branch that caused the class `LinearCombinationTest` to break. Apparently, the class `BigFraction` does no longer contain a `BigFraction(long, long)` constructor, so naturally, the class `LinearCombinationTest` cannot compile. It worked before the merge (you can test it with the master branch).

I'm going to create a JIRA ticket. This is frustrating.

**Comment by Schamschi** [comment]
[JIRA ticket](https://issues.apache.org/jira/browse/NUMBERS-114) created.

**Comment by grimreaper** [comment]
I had fixed it on this branch, and the upstream fix broke my fix. In any case, master is now merged.

**Comment by grimreaper** [comment]
All tests but one test passes now: FieldParametricTest

This class was giving me confusion before too - I have not yet figured out how to create parameterized tests in a similar way to junit 4 via the constructor. I did manage to make this pass by writing an argumentresolver but that seemes like overkill

**Comment by Schamschi** [comment]
@grimreaper 

> I had fixed it on this branch, and the upstream fix broke my fix.

Oh, I'm sorry about that, I obviously forgot to check whether you had already fixed the issue on the branch. Still, apparently this class was not the only one that was broken by the merge of fraction-dev, and since this mess-up occurred on the master branch and not on our migration branch, I think it is better if it is also fixed on the master branch. But it's true, I overlooked the update in this branch. Will try to be more attentive the next time.

**Comment by grimreaper** [comment]
I agree  - it should have been fixed on master and I'm not upset or frustrated my fix was ignored :)

**Comment by Schamschi** [comment]
@grimreaper Excellent :D By the way, I don't know how much progress you've made with FieldParametricTest, nor have I really looked at this class, but the JUnit 5 user guide says that parameterized tests are currently an experimental feature, meaning it could be removed any time with prior notice (it says so in section 7.1 of the user guide). But as I said, I haven't looked at the class at all, I just thought I'd let you know in case you aren't already aware of this.

**Comment by grimreaper** [comment]
@Schamschi  while we're changing stuff - what do you think about static imports for "assertEquals" and friends?

**Comment by grimreaper** [comment]
> the JUnit 5 user guide says that parameterized tests are currently an experimental feature

I did not notice this, but it may mean that I could just simplify the parameters. There aren't too many so auto-generating tests or just doing single tests in a loop might be sufficient.

**Comment by Schamschi** [comment]
@grimreaper 
> what do you think about static imports for "assertEquals" and friends?

I just stumbled upon a curiosity in the class `TestUtils` of the `commons-numbers-core` module, which I've overlooked in my last commit. From looking at the first two methods `TestUtils.assertEquals(double, double, double)` and `TestUtils.assertEquals(String, double, double, double)`, it seems to me that the `assertEquals` method invoked in `TestUtils.assertEquals(double, double, double)` should actually be the one from `TestUtils`, and not the one from `Assert`. Maybe this was originally so, and then somebody carelessly refactored the method to invoke the respective method from `Assert` (it's impossible to tell from the commit history).

I'm not sure if this is an argument against static imports, but in this specific situation, static imports would certainly have caused confusion. Also, I'm not sure whether replacing the explicit `Assert`/`Assertions` references with static imports is within the scope of this branch. I could imagine that the commit history would be easier to follow if we just convert everything from JUnit 4 to its closest JUnit 5 equivalent without changing more than necessary in this branch, and changing things like static imports or replacing try-catch-constructs with assertThrows not before the migration is completely performed.

Ironically, the aforementioned `assertEquals` methods declared in `TestUtils` are completely pointless anyway, because the `assertEquals` methods from JUnit4 `Assert`, as well as from JUnit5 `Assertions` already consider two NaN `double`s equal, so they behave exactly like these methods in `TestUtils`. But then again, fixing this might be outside the scope of this branch.

**Comment by grimreaper** [comment]
I got FieldParametricTest working - it may not be the best way, but at least it passes.

**Comment by grimreaper** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Commons Numbers 1.0-SNAPSHOT:
[INFO]
[INFO] Apache Commons Numbers ............................. SUCCESS [  3.892 s]
[INFO] Apache Commons Numbers Core ........................ SUCCESS [  3.600 s]
[INFO] Apache Commons Numbers Complex ..................... SUCCESS [  2.258 s]
[INFO] Apache Commons Numbers Complex Streams ............. SUCCESS [  2.232 s]
[INFO] Apache Commons Numbers Primes ...................... SUCCESS [  2.030 s]
[INFO] Apache Commons Numbers Quaternion .................. SUCCESS [  2.106 s]
[INFO] Apache Commons Numbers Fraction .................... SUCCESS [  2.121 s]
[INFO] Apache Commons Numbers Angle ....................... SUCCESS [  2.063 s]
[INFO] Apache Commons Numbers Gamma ....................... SUCCESS [  5.229 s]
[INFO] Apache Commons Numbers Combinatorics ............... SUCCESS [  5.304 s]
[INFO] Apache Commons Numbers Arrays ...................... SUCCESS [  2.236 s]
[INFO] Apache Commons Numbers Field ....................... SUCCESS [  2.402 s]
[INFO] Apache Commons Numbers Root Finder ................. SUCCESS [  2.288 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.109 s
[INFO] Finished at: 2019-06-08T17:58:57-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by Schamschi** [comment]
@grimreaper Congratulations! I'll continue with the complex-stream and complex module (working my way up alphabetically from bottom to top, for some reason …).

About the fraction module: I see that you have requested that [pull request #36](https://github.com/apache/commons-numbers/pull/36) be delayed until after the migration to JUnit 5. However, I would be in favor of merging the referenced pull request already before the migration (provided it is updated so that it can be merged with master), because this pull request has been slowly decaying into oblivion ever since I submitted it, which was both before we started working on the migration and also before the fraction-dev branch was merged into master. At the time of its submission, the pull request conflicted with the development on fraction-dev because I wasn't aware of the active development on fraction-dev back then, so the pull request was not merged. Now, fraction-dev has been merged into master, but of course, now the pull request conflicts with master, so again, it cannot be merged.

So there are two options: I either update the pull request so that it can be merged, or I put it to rest, burying it in the depths of unmerged pull requests and have all the work that went into it go to waste. I'm still undecided on this, but in case I opt for the former, I think it would be much less work to reconstruct the changes that have already been applied to the class `FractionTest` in the migration branch (which I would be willing to do) than to refactor the pull request to not only be compatible with the merge of the fraction-dev branch, but also with the migration to JUnit 5.

So I'd suggest that we wait with the fraction module until the pull request is closed, whether it is merged or discarded. What do you think?

**Comment by ebarnhill** [comment]
Sorry about the confusion about fraction-dev. If you can collect these comments into a post for the mailing list and/or a JIRA ticket I will tend to it this week. I had no idea outside modules were calling BigFraction and I'm happy to put the long-based constructor back in.

**Comment by ebarnhill** [comment]
Also, no force pushing please. There is always a way to avoid it. :)

**Comment by Schamschi** [comment]
@ebarnhill Thank you for the offer, but the problem arising from the removal of the long-based constructor in BigFraction has already been [fixed](https://github.com/apache/commons-numbers/commit/c97fc79f4dbebc15128c5bc77afde4c2319ca3c4) after I had created the JIRA ticket which I linked to earlier.

**Comment by grimreaper** [comment]
> However, I would be in favor of merging the referenced pull request already before the migration (provided it is updated so that it can be merged with master), because this pull request has been slowly decaying into oblivion ever since I submitted it,

I didn't actually see that this was you. In that case go ahead and submit it. My main concern was someone causing merge conflicts indefinitely with our work.

**Comment by grimreaper** [comment]
@Schamschi take a look at the current status. Tests still pass, but its more "junit 5" like

**Comment by Schamschi** [comment]
@grimreaper Why did you agree to wait for the pull request #36 to be merged (or closed unmerged) and then go ahead and refactor `FractionTest` anyway? Not only did I replace several `Assert.assertEquals` pairs comparing the numerator and denominator separately with a single call to the method `assertFraction`, which already reduces the number of `Assert` references drastically, but I also added anonymous blocks in the test methods to make them a little less messy, and resolving the conflicts arising from the introduction of these anonymous blocks in a merge or rebase is _very_ laborious – I already did it once yesterday when updating my pull request to be compatible with the changes introduced by the merge of fraction-dev, and the thought of doing it a second time is rather off-putting.

Besides, I don't think `assertEquals(a, b)` and `assertTrue(a.equals(b))` are 100% interchangeable, because, the way I see it, they reflect different intentions, even if they may be functionally equivalent most of the time. Judging by its design and the names for the parameters, `assertEquals(a, b)` is meant for situations where you have a pre-computed (at compile- or runtime), "expected" value, against which an unknown, "actual" value computed at runtime is checked. But there may be situations where both values are unknown, and one is not necessarily more correct than the other, for example, when comparing two hash codes, or when testing the `equals` method itself.

Speaking of testing the `equals` method: Although not done in this case as far as I am aware, I could imagine a scenario where one would want to test of the symmetry of the `equals` method by testing both `a.equals(b)` and `b.equals(a)`. `assertEquals` does not specify whose object's `equals` method is called, so replacing `assertTrue` constructs with `assertEquals` constructs here seems inappropriate. A situation related to this can be found in the class `BigFractionTest`, line 601, where the original code called the `equals` method of `BigFraction` with a `Double` argument:

> `Assert.assertFalse(zero.equals(Double.valueOf(0)));`

So in this case, it is crucial for the validity of the test that the `equals` method of the `BigFraction` instance `zero` is called, and not the `equals` method of the `Double`. However, in its current version, the `equals` method of `Double` is called:

> `Assertions.assertNotEquals(0.0d, zero);`

`0.0d` is implicitly boxed to `Double`, and since `assertNotEquals` calls the `equals` method of the first argument (which is an implementation detailed and not documented), the test becomes useless.

By this logic, there are situations where I find your conversion from `assertTrue` to `assertEquals` absolutely beneficial, for example, the `testParse()` method in the class `ComplexTest` from the "complex" module, or `testMath843()` in `PrecisionTest` in the "Core" module, thank you.

Also, the original parameter order for `assertEquals` in SmallPrimesTest was correct, and your change to the file `ArithmeticUtilsTest` in the commit "Simplify junit" also has the parameters in the wrong order, but I don't have time to fix it now, maybe you can tend to it if you get back here before I do.

**Comment by Schamschi** [comment]
@grimreaper PR [#36](https://github.com/apache/commons-numbers/pull/36) has been merged into master. Since you said it's OK if the pull request is merged, I completely overwrote the previous version of `FractionTest` from this branch with the new version from master when merging master into this branch, and restored the changes that had been made to `FractionTest` in this branch up to that point. From then on, I migrated the file from scratch, meaning I didn't include any of your later changes (this is exactly the scenario I wanted to avoid by agreeing on which pull request should be merged first before any major changes are performed in this branch that would conflict with the other pull request).

I also removed the last unused imports, so the branch is now completely independent of JUnit 4.

I, on my part, am finished with this branch. Do you intend to work any further on it? If not, what to do next? Write to the dev mailing list? I guess the pom.xml will have to be modified to remove any dependency related to JUnit 4, but I'm not sure how, since I didn't understand all of the changes made to it when adding JUnit 5 as a dependency alongside JUnit 4.

In any case, thank you very much for your help.

**Comment by aherbert** [comment]
@Schamschi I would try locally just removing these lines:
```
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-runner</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <scope>test</scope>
    </dependency>
```

These are to support JUnit 4. If your branch has no JUnit 4 then it should be OK.

**Comment by grimreaper** [comment]
> , on my part, am finished with this branch. Do you intend to work any further on it? If not, what to do next? Write to the dev mailing list? 

Yes. We should send it to the list for review. After that we should squash the changes into a single commit and merge.


> I guess the pom.xml will have to be modified to remove any dependency related to JUnit 4, but I'm not sure how, since I didn't understand all of the changes made to it when adding JUnit 5 as a dependency alongside JUnit 4.

I'll follow up with that after the merge.

>  From then on, I migrated the file from scratch, meaning I didn't include any of your later changes (this is exactly the scenario I wanted to avoid by agreeing on which pull request should be merged first before any major changes are performed in this branch that would conflict with the other pull request).

Sorry about that. I got carried away and kind of forgot :/

**Comment by grimreaper** [comment]
Also, thank you for all your help: you did the crux of the work.

**Pull request merged**
